#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 10 11:54:22 2016

@author: ArqSantos
"""
#Begin by importing pandas:
from pandas import Series, DataFrame
import pandas as pd
#INDEXING AND DROPPING

#Starting with a dict of equal length lists:
data = {
        'State':['ohio', 'nevada', 'oklahoma', 'texas', 'louisiana'], 
        'Year':[2000, 2001, 1999, 2003, 2005],
        'Population': [1.5, 1.3, 1.6, 1.2, 2.0]
        }
        
#slightly different:
#create an index first:
old_index = ['1st State', '2nd state', '3rd State', '4th State', '5th State']

#Convert to dataframe, without specifying the indexes, those will be autogenerated:      
dataframe_example = DataFrame(data)
print('First dataframe from the dictionary of equal-length lists.')
#Indexes go from 0 to 4
print(dataframe_example)

#Assign specific set of indexes to dataframe:
dataframe_example.index = old_index
print('Changed indexes to a list of indexes.')
print(dataframe_example)



#similar but not equal to REINDEXING:
#Create new object with data conforming to a new index:
new_index = ['State one', 'State two', 'State three', 'State four', 'State five']
#and then:
b = DataFrame(data = dataframe_example.values, columns = dataframe_example.columns, index = new_index)
print('After creating a new index list to assign to a new df:')
print('A remains unchanged: ')
print(dataframe_example)
print('B is a new dataframe, with new indexes.')
print(b)

#DROP an index along with its values from a dataframe:
#DROP creates a copy of original, then removes the passed arguments (indexes).
#This deletes ROWS.   
c = b.drop(['State two', 'State four'])
print('This is a new DF with some indexes removed using DROP:')
print(c)

#DROP can remove indexes on both axis (rows, horizontal -no axis-, and columns, vertical -axis = 1-):
d = b.drop(['Population'], axis = 1)
print('This is a new DF with a deleted column, using axis = 1:')
print(d)

e = b.drop(['Year'], axis = 1)
print('This is another example of DROPPING a column:')
print(e)





















